
waiting Time
service Time
response time / lead time
queue length
flow efficiency
arrival rate 
service rate
rate limit
little's law


Referência: Masterclass Fundamentos Atemporais para Arquitetos de Software (Elemar Junior)